version: "3"
services:
  # ------- Postgres -------
  postgres:
    image: "postgres:latest"

  # ------- Redis -------
  redis:
    image: "redis:latest"

  # ------- React server -------
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules #bookmark hold
      - ./server:/app # Link host computer files to container files
    environment:
      - REDIS_HOST=redis # "redis" refers to the redis service defined in this file
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres # "postgres" refers to the postgres service defined in this file
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  # ------- Client -------
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  # ------- Worker -------
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis # "redis" refers to the redis service defined in this file
      - REDIS_PORT=6379

  # ------- Nginx -------
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
